[package]
name = "backup_emergency"
version = "0.1.0"
edition = "2021"

[dependencies]
device_query = "2.1.0"
scrap = "0.5.0"

winit = "0.28"
pixels = "0.13"
rusttype = "0.9"

sysinfo = "0.31.4"

toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
regex = "1.11.0"
chrono = "0.4"