# Configurazione backup
[backup]
source_directory = "/Users/paolomuccilli/Desktop/massimino"
destination_directory = "/Users/paolomuccilli" #"C:\\Users\\maxim\\Desktop\\file_backup\\destination_folder"
file_types = ["mm", "rs", "jpg", "*"]  # Tipi di file da includere nel backup

[cpu_logging]
log_path = "/Users/paolomuccilli/Desktop"  # Intervallo per log del consumo CPU